initial_path: null
sample_data_path: null
port: 8050
debug: false
app:
  title: "MEDS INSPECT"
  suppress_callback_exceptions: true
limits:
  subject_ids: 100
  coding_dict: 1000
  search_results: 1000
